import { slugify } from './slugify.js';

/**
 * Reference seed data compiled from public/official recruitment news (July 2026).
 * NOT scraped from sarkariresult.com (copyright).
 * Always verify vacancy, dates and eligibility on the official website before applying.
 */

const commonDocs =
  'Photo, Signature, Aadhaar / ID Proof, Educational Certificates, Caste Certificate (if applicable), EWS Certificate (if applicable), PwBD Certificate (if applicable)';

const commonHowTo =
  '1. Visit the official website using Apply Online link.\n2. Complete One-Time Registration (if new user).\n3. Login with Registration Number / Password.\n4. Fill personal, educational and contact details carefully.\n5. Upload photo, signature and documents in required format.\n6. Pay application fee online (if applicable).\n7. Submit form and take printout of confirmation page.';

export const samplePosts = [
  // ========== CURRENTLY OPEN / HOT (as of mid-July 2026) ==========
  {
    title: 'IBPS PO / MT CRP-XVI Online Form 2026',
    category: 'latest-job',
    organization: 'Institute of Banking Personnel Selection',
    department: 'IBPS',
    postName: 'Probationary Officer / Management Trainee',
    totalVacancies: 6715,
    vacancyDetails:
      'Approximately 6,715 PO/MT vacancies in participating Public Sector Banks under CRP-PO/MTs-XVI (bank-wise as per official annexure).',
    qualification: 'Bachelor Degree in Any Stream from a Recognized University',
    ageLimit: '20–30 Years (Age Relaxation as per IBPS / Govt rules)',
    applicationFee: 'General / OBC / EWS: ₹850 | SC / ST / PwBD: ₹175',
    salary: 'As per bank PO scale (approx in-hand varies by posting) + allowances',
    selectionProcess: 'Prelims CBT → Mains CBT → Interview → Provisional Allotment',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'IBPS PO 2026 online form is LIVE. Last date to apply: 21 July 2026. Prelims: 22–23 August 2026. Total ~6,715 vacancies.',
    content: `<p><strong>Status (reference July 2026):</strong> Online registration is open for IBPS CRP PO/MT.</p>
<p><strong>Apply:</strong> 01 July 2026 to <strong>21 July 2026</strong>.</p>
<p><strong>Exam:</strong> Prelims 22 &amp; 23 August 2026; Mains 04 October 2026 (as per public notices).</p>
<p><strong>Official site only:</strong> <a href="https://www.ibps.in/" rel="noopener noreferrer">ibps.in</a>. Always read the official PDF before applying.</p>`,
    importantDates: {
      notificationDate: '01 July 2026',
      startDate: '01 July 2026',
      lastDate: '21 July 2026',
      examDate: '22–23 Aug 2026 (Prelims)',
      admitCardDate: 'Before Exam',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://www.ibps.in/',
      officialNotification: 'https://www.ibps.in/',
      officialWebsite: 'https://www.ibps.in/',
    },
    tags: ['IBPS', 'PO', 'Banking', 'Open Form'],
    isFeatured: true,
  },
  {
    title: 'RRB ALP Recruitment 2026 Online Form',
    category: 'latest-job',
    organization: 'Railway Recruitment Board',
    department: 'RRB / Indian Railways',
    postName: 'Assistant Loco Pilot (ALP)',
    totalVacancies: 11127,
    vacancyDetails:
      'Around 11,127 Assistant Loco Pilot vacancies (check latest CEN PDF on RRB websites for exact zone-wise numbers).',
    qualification: 'Matriculation / SSLC + ITI / Diploma in relevant trade (as per CEN)',
    ageLimit: '18–30 Years (Relaxation as per Railway rules)',
    applicationFee:
      'General: as per RRB CEN | SC/ST/Female/ExSM/PwBD: concessional / refundable as per notice',
    salary: 'Level-2 pay matrix (7th CPC) + allowances',
    selectionProcess: 'CBT-1 → CBT-2 → CBAT → Document Verification → Medical',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'RRB ALP 2026 notification for 11,000+ Assistant Loco Pilot posts. Apply only via official RRB portals.',
    content: `<p><strong>RRB ALP 2026:</strong> Major railway recruitment for Assistant Loco Pilot.</p>
<p>Confirm start/last dates and fee on your regional RRB site or <a href="https://www.rrbcdg.gov.in/" rel="noopener noreferrer">rrbcdg.gov.in</a>.</p>
<p>Eligibility depends on trade/qualification mentioned in the official CEN.</p>`,
    importantDates: {
      notificationDate: '2026',
      startDate: 'As per CEN',
      lastDate: 'Check Official Notice',
      examDate: 'To be announced',
      admitCardDate: 'Before CBT',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://www.rrbcdg.gov.in/',
      officialNotification: 'https://www.rrbcdg.gov.in/',
      officialWebsite: 'https://indianrailways.gov.in/',
    },
    tags: ['Railway', 'RRB', 'ALP', '11th Pass'],
    isFeatured: true,
  },
  {
    title: 'RRB Technician Recruitment 2026',
    category: 'latest-job',
    organization: 'Railway Recruitment Board',
    department: 'RRB',
    postName: 'Technician',
    totalVacancies: 6557,
    vacancyDetails: 'Approximately 6,500+ Technician posts (verify exact count in official CEN).',
    qualification: 'Matric + ITI / relevant technical qualification (post-wise)',
    ageLimit: '18–33 Years (as per CEN)',
    applicationFee: 'As per RRB Technician CEN',
    salary: 'Level as per post (7th CPC)',
    selectionProcess: 'CBT → Document Verification → Medical',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'RRB Technician recruitment ~6,557 posts. Public reports last date around 29 July 2026 — confirm on official site.',
    content: `<p>Apply only through official Railway Recruitment Board websites. Dates may change; verify before paying fee.</p>`,
    importantDates: {
      notificationDate: '2026',
      startDate: 'As notified',
      lastDate: '29 July 2026 (verify official)',
      examDate: 'To be announced',
      admitCardDate: 'Before Exam',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://www.rrbcdg.gov.in/',
      officialNotification: 'https://www.rrbcdg.gov.in/',
      officialWebsite: 'https://indianrailways.gov.in/',
    },
    tags: ['Railway', 'Technician', 'RRB'],
    isFeatured: true,
  },
  {
    title: 'SBI PO Recruitment 2026 Online Form',
    category: 'latest-job',
    organization: 'State Bank of India',
    department: 'SBI',
    postName: 'Probationary Officer',
    totalVacancies: 1500,
    vacancyDetails: 'About 1,500 Probationary Officer vacancies (as per public reports for 2026 cycle).',
    qualification: 'Graduation in Any Discipline',
    ageLimit: '21–30 Years (Relaxation as per SBI rules)',
    applicationFee: 'General / EWS / OBC: as per notice | SC / ST / PwBD: concessional',
    salary: 'SBI PO pay scale + allowances (higher among PSU banks)',
    selectionProcess: 'Prelims → Mains → Psychometric / Interview / Group Exercise',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'SBI PO 2026 for ~1,500 posts. Check sbi.co.in / sbi.co.in/careers for current status of apply window.',
    content: `<p>Official career portal: <a href="https://sbi.co.in/web/careers" rel="noopener noreferrer">sbi.co.in/careers</a>.</p>
<p>If apply window is closed, keep checking for next phase / admit card / result updates.</p>`,
    importantDates: {
      notificationDate: '2026',
      startDate: 'As notified',
      lastDate: 'Check Official (reported early July 2026)',
      examDate: 'To be announced',
      admitCardDate: 'Before Exam',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://sbi.co.in/web/careers',
      officialNotification: 'https://sbi.co.in/web/careers',
      officialWebsite: 'https://sbi.co.in/',
    },
    tags: ['SBI', 'PO', 'Banking'],
    isFeatured: true,
  },
  {
    title: 'UPSC Various Posts Advt (Prosecutor, Specialist etc.) 2026',
    category: 'latest-job',
    organization: 'Union Public Service Commission',
    department: 'UPSC',
    postName: 'Prosecutor, Specialist and Other Posts',
    totalVacancies: 48,
    vacancyDetails: 'Around 48 posts including Prosecutor, Specialist and others (check UPSC Advt. No. for details).',
    qualification: 'LLB / MBBS / DNB / M.Sc / DM as per post',
    ageLimit: 'As per individual post in UPSC advertisement',
    applicationFee: 'As per UPSC rules',
    salary: 'As per post / pay level',
    selectionProcess: 'As per UPSC advertisement (written / interview / shortlisting)',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'UPSC multi-post advertisement — last date reported 31 July 2026. Apply at upsconline.nic.in.',
    content: `<p>Visit <a href="https://upsc.gov.in/" rel="noopener noreferrer">upsc.gov.in</a> and <a href="https://upsconline.nic.in/" rel="noopener noreferrer">upsconline.nic.in</a> for the exact advertisement PDF and apply link.</p>`,
    importantDates: {
      notificationDate: 'July 2026',
      startDate: 'July 2026',
      lastDate: '31 July 2026',
      examDate: 'As notified',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://upsconline.nic.in/',
      officialNotification: 'https://upsc.gov.in/',
      officialWebsite: 'https://upsc.gov.in/',
    },
    tags: ['UPSC', 'Open Form'],
  },
  {
    title: 'RITES Assistant Manager Online Form 2026',
    category: 'latest-job',
    organization: 'RITES Limited',
    department: 'RITES (PSU)',
    postName: 'Assistant Manager',
    totalVacancies: 24,
    vacancyDetails: '24 Assistant Manager posts (engineering discipline as per notice).',
    qualification: 'B.Tech / B.E. in relevant branch',
    ageLimit: 'As per RITES notification',
    applicationFee: 'As per official notice',
    salary: 'IDA pay scale as applicable to RITES',
    selectionProcess: 'As per RITES recruitment rules (CBT / interview)',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription: 'RITES Assistant Manager — 24 posts. Last date reported: 17 August 2026.',
    content: `<p>Apply via official RITES career page. Confirm dates on <a href="https://www.rites.com/" rel="noopener noreferrer">rites.com</a>.</p>`,
    importantDates: {
      notificationDate: '18 July 2026',
      startDate: '18 July 2026',
      lastDate: '17 August 2026',
      examDate: 'To be announced',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://www.rites.com/',
      officialWebsite: 'https://www.rites.com/',
      officialNotification: 'https://www.rites.com/',
    },
    tags: ['RITES', 'Engineering', 'PSU'],
  },

  // ========== RECENTLY CLOSED / EXAM UPCOMING ==========
  {
    title: 'SSC CGL 2026 Combined Graduate Level Exam',
    category: 'latest-job',
    organization: 'Staff Selection Commission',
    department: 'SSC',
    postName: 'Combined Graduate Level (Group B & C)',
    totalVacancies: 12256,
    vacancyDetails:
      'About 12,256 vacancies (tentative). Final vacancies as per SSC notice. Apply window was May–June 2026.',
    qualification: 'Bachelor Degree in Any Stream from Recognized University',
    ageLimit: '18–32 Years (as on 01 August 2026; relaxation as per rules)',
    applicationFee: 'General / OBC / EWS: ₹100 | SC / ST / Female / ESM / PwBD: Nil',
    salary: 'Pay Level 4 to Level 8 as per post + allowances',
    selectionProcess: 'Tier-I CBT → Tier-II CBT → DV / Medical as applicable',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    shortDescription:
      'SSC CGL 2026 for ~12,256 posts. Application closed (extended till ~25 June 2026). Tier-I expected Aug–Sep 2026.',
    content: `<p><strong>Official notice (SSC):</strong> Online applications were accepted from 21.05.2026; last dates extended around late June 2026.</p>
<p><strong>Next steps:</strong> Admit card / city intimation on regional SSC websites before Tier-I.</p>
<p>Portal: <a href="https://ssc.gov.in/" rel="noopener noreferrer">ssc.gov.in</a></p>`,
    importantDates: {
      notificationDate: '21 May 2026',
      startDate: '21 May 2026',
      lastDate: '25 June 2026 (extended)',
      examDate: 'August–September 2026 (Tier-I tentative)',
      admitCardDate: 'Before Tier-I',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://ssc.gov.in/',
      officialNotification: 'https://ssc.gov.in/',
      officialWebsite: 'https://ssc.gov.in/',
      downloadAdmitCard: 'https://ssc.gov.in/',
    },
    tags: ['SSC', 'CGL', 'Graduate'],
    isFeatured: true,
  },

  // ========== RESULTS ==========
  {
    title: 'NEET UG / Re-NEET 2026 Result',
    category: 'result',
    organization: 'National Testing Agency',
    department: 'NTA',
    postName: 'NEET (UG) 2026',
    totalVacancies: 0,
    vacancyDetails: 'Result / scorecard for medical entrance — not a job vacancy.',
    qualification: 'Appeared in NEET UG 2026 / Re-exam',
    ageLimit: 'As per NMC / NTA rules',
    applicationFee: 'Not applicable for result',
    salary: 'Not applicable',
    selectionProcess: 'NEET score → MCC / State counselling',
    documentsRequired: 'Application Number and Password / DOB',
    howToApply:
      '1. Open neet.nta.nic.in\n2. Click Result / Scorecard link.\n3. Login with application number and password.\n4. Download scorecard PDF.\n5. Use score for counselling as per MCC / state schedule.',
    shortDescription:
      'NTA has declared NEET UG / Re-NEET 2026 result (reported 16 July 2026). Check scorecard on official NTA portal.',
    content: `<p><strong>Result status:</strong> Public reports confirm result around <strong>16 July 2026</strong> at neet.nta.nic.in.</p>
<p>Re-exam was scheduled around 21 June 2026 after earlier cycle updates. Always download scorecard only from official NTA site.</p>`,
    importantDates: {
      notificationDate: '2026',
      startDate: '—',
      lastDate: '—',
      examDate: '21 June 2026 (Re-exam as reported)',
      admitCardDate: 'June 2026',
      resultDate: '16 July 2026',
    },
    links: {
      checkResult: 'https://neet.nta.nic.in/',
      officialWebsite: 'https://nta.ac.in/',
      officialNotification: 'https://neet.nta.nic.in/',
    },
    tags: ['NEET', 'NTA', 'Result'],
    isFeatured: true,
  },
  {
    title: 'IBPS PO Final Result Updates (Previous Cycle)',
    category: 'result',
    organization: 'IBPS',
    department: 'IBPS',
    postName: 'Probationary Officer',
    shortDescription:
      'Previous CRP PO cycle final results / scorecards on ibps.in. New CRP-XVI form is open separately.',
    qualification: 'As per previous notification',
    ageLimit: 'As per previous notification',
    applicationFee: 'Not applicable',
    salary: 'Bank PO scale',
    selectionProcess: 'Prelims → Mains → Interview',
    documentsRequired: 'Registration Number and Password',
    howToApply:
      '1. Go to ibps.in\n2. Open CRP PO result link if available.\n3. Login and download scorecard.',
    content: `<p>Use official IBPS website only. Do not share login details on third-party sites.</p>`,
    importantDates: {
      resultDate: 'As declared on ibps.in',
      examDate: 'As conducted',
      notificationDate: '—',
      startDate: '—',
      lastDate: '—',
      admitCardDate: '—',
    },
    links: {
      checkResult: 'https://www.ibps.in/',
      officialWebsite: 'https://www.ibps.in/',
    },
    tags: ['IBPS', 'PO', 'Result'],
  },

  // ========== ADMIT CARDS ==========
  {
    title: 'CSBC Bihar Police Constable Operator Admit Card 2026',
    category: 'admit-card',
    organization: 'Central Selection Board of Constable',
    department: 'CSBC Bihar',
    postName: 'Constable (Operator)',
    totalVacancies: 993,
    vacancyDetails: '993 Constable (Operator) posts under Advt. No. 02/2026 (as reported).',
    qualification: 'As per CSBC Advt. 02/2026',
    ageLimit: 'As per advertisement',
    applicationFee: 'Already paid during application',
    salary: 'As per Bihar Police pay rules',
    selectionProcess: 'Written Exam → further stages as per notice',
    documentsRequired: 'Printed Admit Card + Original Photo ID',
    howToApply:
      '1. Visit csbc.bihar.gov.in or apply-csbc.com admit card link.\n2. Enter registration details.\n3. Download e-Admit Card.\n4. Check exam city, date and reporting time.\n5. Carry photo ID to centre.',
    shortDescription:
      'CSBC has issued exam city / e-Admit Card for Constable Operator (Advt 02/2026). Download from official CSBC links.',
    content: `<p>Official board: <a href="https://csbc.bihar.gov.in/" rel="noopener noreferrer">csbc.bihar.gov.in</a></p>
<p>Application period was March 2026 (as reported). Admit card / city details released via CSBC notices (June 2026).</p>`,
    importantDates: {
      notificationDate: '2026',
      startDate: '01 March 2026',
      lastDate: '31 March 2026',
      examDate: 'As on admit card',
      admitCardDate: 'June 2026 onwards',
      resultDate: 'To be announced',
    },
    links: {
      downloadAdmitCard: 'https://csbc.bihar.gov.in/',
      officialWebsite: 'https://csbc.bihar.gov.in/',
      officialNotification: 'https://csbc.bihar.gov.in/',
    },
    tags: ['Bihar', 'Police', 'Admit Card', 'CSBC'],
    isFeatured: true,
  },
  {
    title: 'SSC CGL 2026 Admit Card / City Intimation',
    category: 'admit-card',
    organization: 'Staff Selection Commission',
    department: 'SSC',
    postName: 'CGL Tier-I',
    shortDescription:
      'Download region-wise city intimation and admit card for SSC CGL Tier-I from SSC regional websites.',
    qualification: 'Graduate (already applied)',
    ageLimit: 'As per CGL 2026 notice',
    applicationFee: 'Already paid',
    salary: 'As per allotted post',
    selectionProcess: 'Tier-I then Tier-II',
    documentsRequired: 'Admit Card + Original Photo ID',
    howToApply:
      '1. Open ssc.gov.in or your regional SSC site.\n2. Click Admit Card / Status.\n3. Login with Registration ID and password.\n4. Download and print admit card.',
    content: `<p>Tier-I is tentatively scheduled August–September 2026. Admit cards release a few days before exam, region-wise.</p>`,
    importantDates: {
      examDate: 'August–September 2026 (tentative)',
      admitCardDate: 'Before exam',
      notificationDate: '21 May 2026',
      startDate: '—',
      lastDate: '—',
      resultDate: '—',
    },
    links: {
      downloadAdmitCard: 'https://ssc.gov.in/',
      officialWebsite: 'https://ssc.gov.in/',
    },
    tags: ['SSC', 'CGL', 'Admit Card'],
  },

  // ========== ANSWER KEY ==========
  {
    title: 'NEET UG 2026 Answer Key / Final Key Updates',
    category: 'answer-key',
    organization: 'National Testing Agency',
    department: 'NTA',
    postName: 'NEET (UG)',
    shortDescription: 'Check provisional / final answer key notices on neet.nta.nic.in and nta.ac.in.',
    qualification: 'NEET candidates',
    ageLimit: '—',
    applicationFee: 'Challenge fee if applicable as per NTA',
    salary: '—',
    selectionProcess: 'Key challenge → Final key → Result',
    documentsRequired: 'Application number to view response / key',
    howToApply:
      '1. Visit neet.nta.nic.in\n2. Open Answer Key / Challenge link when live.\n3. Login and download OMR / key.\n4. Submit challenges only within official window.',
    content: `<p>Only NTA keys are valid for final scoring. Coaching keys are unofficial.</p>`,
    importantDates: {
      examDate: '2026 cycle',
      resultDate: 'July 2026',
      notificationDate: '—',
      startDate: '—',
      lastDate: 'Challenge window as notified',
      admitCardDate: '—',
    },
    links: {
      answerKey: 'https://neet.nta.nic.in/',
      officialWebsite: 'https://nta.ac.in/',
    },
    tags: ['NEET', 'Answer Key'],
  },

  // ========== SYLLABUS ==========
  {
    title: 'SSC CGL 2026 Syllabus Tier I & II',
    category: 'syllabus',
    organization: 'Staff Selection Commission',
    department: 'SSC',
    postName: 'CGL',
    shortDescription: 'Official tier-wise syllabus for SSC CGL Examination 2026.',
    qualification: 'Graduate',
    ageLimit: 'As per CGL',
    applicationFee: '—',
    salary: '—',
    selectionProcess: 'Tier-I and Tier-II syllabus based',
    documentsRequired: '—',
    howToApply: 'Download syllabus from official SSC CGL notice PDF on ssc.gov.in.',
    content: `<p><strong>Tier-I:</strong> General Intelligence &amp; Reasoning, General Awareness, Quantitative Aptitude, English Comprehension.</p>
<p><strong>Tier-II:</strong> Mathematical Abilities, Reasoning, English, General Awareness, Computer Knowledge, and post-specific modules where applicable.</p>
<p>Follow negative marking scheme as per latest SSC notice.</p>`,
    importantDates: {
      notificationDate: 'With CGL 2026 notice',
      startDate: '—',
      lastDate: '—',
      examDate: 'Aug–Sep 2026 tentative',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      officialNotification: 'https://ssc.gov.in/',
      officialWebsite: 'https://ssc.gov.in/',
    },
    tags: ['SSC', 'Syllabus', 'CGL'],
  },
  {
    title: 'IBPS PO 2026 Exam Pattern & Syllabus',
    category: 'syllabus',
    organization: 'IBPS',
    department: 'IBPS',
    postName: 'PO / MT',
    shortDescription: 'Prelims and Mains pattern for IBPS PO CRP-XVI.',
    qualification: 'Graduate',
    ageLimit: '20–30',
    applicationFee: '—',
    salary: '—',
    selectionProcess: 'Prelims + Mains + Interview',
    documentsRequired: '—',
    howToApply: 'Read detailed notification PDF on ibps.in for topic-wise syllabus.',
    content: `<p><strong>Prelims:</strong> English, Quantitative Aptitude, Reasoning Ability.</p>
<p><strong>Mains:</strong> Reasoning &amp; Computer, General/Economy/Banking Awareness, English, Data Analysis &amp; Interpretation, Descriptive English.</p>`,
    importantDates: {
      examDate: 'Prelims Aug 2026',
      notificationDate: 'July 2026',
      startDate: '—',
      lastDate: '—',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      officialWebsite: 'https://www.ibps.in/',
      officialNotification: 'https://www.ibps.in/',
    },
    tags: ['IBPS', 'Syllabus'],
  },

  // ========== ADMISSION ==========
  {
    title: 'NVS Class 6 Admission 2027 Apply Online',
    category: 'admission',
    organization: 'Navodaya Vidyalaya Samiti',
    department: 'NVS',
    postName: 'JNVST Class VI Admission',
    shortDescription:
      'Navodaya Class 6 admission process — last date reported around 31 July 2026. Confirm on navodaya.gov.in.',
    qualification: 'Class 5 studying / as per JNVST eligibility',
    ageLimit: 'As per NVS prospectus',
    applicationFee: 'As per NVS (often free / nominal)',
    salary: 'Not applicable',
    selectionProcess: 'Jawahar Navodaya Vidyalaya Selection Test (JNVST)',
    documentsRequired: 'Photo, DOB proof, Study certificate as per prospectus',
    howToApply: commonHowTo,
    content: `<p>Official information: <a href="https://navodaya.gov.in/" rel="noopener noreferrer">navodaya.gov.in</a></p>`,
    importantDates: {
      startDate: 'As notified',
      lastDate: '31 July 2026 (verify official)',
      examDate: 'As per JNVST schedule',
      notificationDate: '2026',
      admitCardDate: 'Before test',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://navodaya.gov.in/',
      officialWebsite: 'https://navodaya.gov.in/',
    },
    tags: ['NVS', 'Admission', 'Class 6'],
    isFeatured: true,
  },
  {
    title: 'NTA AIAPGET 2026 Apply Online',
    category: 'admission',
    organization: 'National Testing Agency',
    department: 'NTA / AYUSH',
    postName: 'AIAPGET',
    shortDescription:
      'All India AYUSH Post Graduate Entrance Test — last date reported 30 July 2026.',
    qualification: 'BAMS / BUMS / BSMS / BHMS as applicable',
    ageLimit: 'As per NTA AIAPGET brochure',
    applicationFee: 'As per NTA fee chart',
    salary: 'Not applicable',
    selectionProcess: 'AIAPGET → counselling',
    documentsRequired: commonDocs,
    howToApply: commonHowTo,
    content: `<p>Check <a href="https://nta.ac.in/" rel="noopener noreferrer">nta.ac.in</a> and AIAPGET portal for brochure and apply link.</p>`,
    importantDates: {
      startDate: 'As notified',
      lastDate: '30 July 2026 (verify official)',
      examDate: 'As notified',
      notificationDate: '2026',
      admitCardDate: 'Before exam',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://nta.ac.in/',
      officialWebsite: 'https://nta.ac.in/',
    },
    tags: ['AIAPGET', 'AYUSH', 'Admission'],
  },
  {
    title: 'CTET September 2026 Exam',
    category: 'admission',
    organization: 'Central Board of Secondary Education',
    department: 'CBSE / CTET',
    postName: 'Central Teacher Eligibility Test',
    shortDescription:
      'CTET September 2026 — exam reported on 6 September 2026. Application window was May–June 2026.',
    qualification: 'As per CTET eligibility (D.El.Ed / B.Ed etc.)',
    ageLimit: 'No upper age limit for CTET',
    applicationFee: 'As paid during registration',
    salary: 'Eligibility test — not a job',
    selectionProcess: 'Paper I / Paper II CBT',
    documentsRequired: 'Admit card when released',
    howToApply: 'Login at ctet.nic.in for admit card / result after exam.',
    content: `<p>Portal: <a href="https://ctet.nic.in/" rel="noopener noreferrer">ctet.nic.in</a></p>`,
    importantDates: {
      notificationDate: '11 May 2026',
      startDate: '11 May 2026',
      lastDate: '10 June 2026',
      examDate: '06 September 2026',
      admitCardDate: 'Before exam',
      resultDate: 'To be announced',
    },
    links: {
      applyOnline: 'https://ctet.nic.in/',
      officialWebsite: 'https://ctet.nic.in/',
      downloadAdmitCard: 'https://ctet.nic.in/',
    },
    tags: ['CTET', 'Teaching'],
  },

  // ========== IMPORTANT ==========
  {
    title: 'Aadhaar Card Download / Update Online',
    category: 'important',
    organization: 'UIDAI',
    department: 'UIDAI',
    postName: 'Aadhaar Services',
    shortDescription: 'Download e-Aadhaar or update details on myAadhaar portal.',
    qualification: '—',
    ageLimit: '—',
    applicationFee: 'As per UIDAI (many services free online)',
    salary: '—',
    selectionProcess: 'OTP / biometric authentication',
    documentsRequired: 'Aadhaar number, registered mobile',
    howToApply:
      '1. Visit myaadhaar.uidai.gov.in\n2. Login with Aadhaar + OTP.\n3. Download e-Aadhaar or raise update request.',
    content: `<p>Official: <a href="https://myaadhaar.uidai.gov.in/" rel="noopener noreferrer">myaadhaar.uidai.gov.in</a></p>`,
    importantDates: {
      notificationDate: 'Always available',
      startDate: 'Online',
      lastDate: '—',
      examDate: '—',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://myaadhaar.uidai.gov.in/',
      officialWebsite: 'https://uidai.gov.in/',
    },
    tags: ['Aadhaar', 'UIDAI'],
  },
  {
    title: 'PAN Card Apply / Correction Online',
    category: 'important',
    organization: 'NSDL / Income Tax',
    department: 'Income Tax Department',
    postName: 'PAN',
    shortDescription: 'New PAN or correction through official NSDL / UTIITSL portals.',
    qualification: '—',
    ageLimit: '—',
    applicationFee: 'As per NSDL / UTIITSL',
    salary: '—',
    selectionProcess: 'Online form + payment → e-PAN',
    documentsRequired: 'Photo, ID, Address, DOB proof',
    howToApply: commonHowTo,
    content: `<p>Use only official portals linked from <a href="https://www.incometax.gov.in/" rel="noopener noreferrer">incometax.gov.in</a>.</p>`,
    importantDates: {
      notificationDate: 'Always available',
      startDate: 'Online',
      lastDate: '—',
      examDate: '—',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html',
      officialWebsite: 'https://www.incometax.gov.in/',
    },
    tags: ['PAN'],
  },

  // ========== CERTIFICATE ==========
  {
    title: 'Income Certificate Online Apply (State e-District)',
    category: 'certificate',
    organization: 'State e-District / CSC',
    department: 'Revenue',
    postName: 'Income Certificate',
    shortDescription: 'Apply via your state e-District / Jan Seva / CSC portal.',
    qualification: '—',
    ageLimit: '—',
    applicationFee: 'State-wise',
    salary: '—',
    selectionProcess: 'Online apply → verification → download',
    documentsRequired: 'Aadhaar, Address proof, Income proof as per state',
    howToApply:
      '1. Open your state e-District portal.\n2. Login with mobile / Aadhaar.\n3. Select Income Certificate.\n4. Upload documents and submit.\n5. Download after approval.',
    content: `<p>Process differs by state. Prefer official state government portals only.</p>`,
    importantDates: {
      notificationDate: 'State service',
      startDate: 'Online',
      lastDate: '—',
      examDate: '—',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://www.india.gov.in/',
      officialWebsite: 'https://www.india.gov.in/',
    },
    tags: ['Income Certificate'],
  },
  {
    title: 'Caste Certificate Online Apply',
    category: 'certificate',
    organization: 'State Revenue / Social Welfare',
    department: 'State Government',
    postName: 'SC / ST / OBC Certificate',
    shortDescription: 'Apply online for caste certificate on state portals.',
    qualification: '—',
    ageLimit: '—',
    applicationFee: 'State-wise',
    salary: '—',
    selectionProcess: 'Application → enquiry → certificate',
    documentsRequired: 'Aadhaar, Address, Caste proof, Photo',
    howToApply:
      '1. State e-District login.\n2. Select Caste Certificate service.\n3. Fill form and upload proofs.\n4. Track status and download.',
    content: `<p>For central jobs you may need certificate in prescribed central format — check vacancy notice.</p>`,
    importantDates: {
      notificationDate: 'State service',
      startDate: 'Online',
      lastDate: '—',
      examDate: '—',
      admitCardDate: '—',
      resultDate: '—',
    },
    links: {
      applyOnline: 'https://www.india.gov.in/',
      officialWebsite: 'https://www.india.gov.in/',
    },
    tags: ['Caste Certificate'],
  },
];

export function buildSeedDocuments(adminId) {
  return samplePosts.map((p, i) => ({
    ...p,
    slug: `${slugify(p.title)}-${i + 1}`,
    createdBy: adminId,
    publishedAt: new Date(Date.now() - i * 3600_000 * 5),
    isActive: true,
  }));
}
